package ch.hslu.appe.fbs.common.permission;

public enum UserPermissions {
    ADMIN,
    GET_CUSTOMER,
    GET_ALL_CUSTOMERS,
    GET_ORDER,
    GET_ALL_ORDERS,
    GET_REMINDER,
    GET_ALL_REMINDERS,
    GET_ITEM,
    GET_ALL_ITEMS,
    GET_REORDER,
    GET_ALL_REORDERS,
    CREATE_CUSTOMER,
    EDIT_CUSTOMER,
    DELETE_CUSTOMER,
    CREATE_ORDER,
    EDIT_ORDER,
    CANCEL_ORDER,
    ADD_ITEM,
    EDIT_ITEM,
    DELETE_ITEM,
    VIEW_LOGS,
    MARK_REORDER_DELIVERED
}
